dist: bionic
services:
- docker
language: go
go:
- "1.13.x"

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh

script:
- go mod download
- make docscheck
- make lint
- make test
- make vet

branches:
  only:
  - master

matrix:
  fast_finish: true
  allow_failures:
  - go: tip
