name: Integration tests
on:
  workflow_dispatch: null
  push:
    branches:
      - main
jobs:
  integration_tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2
      - run: make testacc
        env:
          LINODE_TOKEN: ${{ secrets.DX_LINODE_TOKEN }}
